[package]
name = "youtube-downloader"
version = "0.1.0"
authors = ["smoqadam <phpro.ir@gmail.com>"]

[dependencies]
hyper="*"
hyper-native-tls="*"
pbr="*"

[[bin]]
name = "youtube-downloader"
path = "src/main.rs"
